export const LOADER = 'LOADER';
export const SETPROFILEDATA = 'SETPROFILEDATA';
export const SETADDRESSLIST = 'SETADDRESSLIST';
export const SETCARTLIST = 'SETCARTLIST';
export const SETADDRESSSELECT = 'SETADDRESSSELECT';
export const SETNEWADDRESS = 'SETNEWADDRESS';
export const SETPICKUPMODE = 'SETPICKUPMODE';
export const ASKPICKUPMODE = 'ASKPICKUPMODE';
export const SHOWALERT = 'SHOWALERT';
export const SETFCMTOKEN = 'SETFCMTOKEN';
export const SETCOUNTRY = 'SETCOUNTRY';

